#
# Makefile for the linux kernel.
#

obj-$(CONFIG_MACH_BCM2708) 	+= clock.o bcm2708.o armctrl.o vcio.o power.o dma.o
obj-$(CONFIG_BCM2708_BUTTONS)		+= bcm2708_buttons.o
obj-$(CONFIG_BCM2708_TOUCHSCREEN)		+= bcm2708_touchscreen.o
obj-$(CONFIG_BCM2708_LEDS)		+= bcm2708_leds.o
