/*
 * Internal EEPROM addresses
 */

#define EEPROM_LX_ERASED_VALUE	(0xff)
#define EEPROM_LX_SIZE_IN_BYTES	(128)
#define EEPROM_LX_MAX_ADDR	(EEPROM_NETBOOK2_SIZE_IN_BYTES - 1)

/* Address 0 - 9 */
#define EEPROM_LX_TERMINAL_SERIAL_NUMBER_SIZE		(10)
#define EEPROM_LX_TERMINAL_SERIAL_NUMBER_ADDRESS	(0)

/* Address 10 - 19 */
#define EEPROM_LX_HARDWARE_SERIAL_NUMBER_SIZE	(10)
#define EEPROM_LX_HARDWARE_SERIAL_NUMBER_ADDRESS \
	(EEPROM_LX_TERMINAL_SERIAL_NUMBER_ADDRESS +\
	 EEPROM_LX_TERMINAL_SERIAL_NUMBER_SIZE)

/* Address 20 */
#define EEPROM_LX_HARDWARE_REVISION_SIZE	(1)
#define EEPROM_LX_HARDWARE_REVISION_ADDRESS \
	(EEPROM_LX_HARDWARE_SERIAL_NUMBER_ADDRESS +\
	 EEPROM_LX_HARDWARE_SERIAL_NUMBER_SIZE)

/* Address 21 - 40 */
#define EEPROM_LX_TOUCH_CALIBRATION_DATA_SIZE	(20)
#define EEPROM_LX_TOUCH_CALIBRATION_DATA_ADDRESS \
	(EEPROM_LX_HARDWARE_REVISION_ADDRESS +\
	 EEPROM_LX_HARDWARE_REVISION_SIZE)

/* Address 41 */
#define EEPROM_LX_KEYBOARD_TYPE_SIZE		(1)
#define EEPROM_LX_KEYBOARD_TYPE_ADDRESS \
	(EEPROM_LX_TOUCH_CALIBRATION_DATA_ADDRESS +\
	 EEPROM_LX_TOUCH_CALIBRATION_DATA_SIZE)

/* Address 42 - 43 */
#define EEPROM_LX_BATTERY_CAPACITY_SIZE		(2)
#define EEPROM_LX_BATTERY_CAPACITY_ADDRESS \
	(EEPROM_LX_KEYBOARD_TYPE_ADDRESS +\
	 EEPROM_LX_KEYBOARD_TYPE_SIZE)

/* Address 44 */
#define EEPROM_LX_BOOST_SECURITY_SIZE		(1)
#define EEPROM_LX_BOOST_SECURITY_ADDRESS \
	(EEPROM_LX_BATTERY_CAPACITY_ADDRESS +\
	 EEPROM_LX_BATTERY_CAPACITY_SIZE)

#define EEPROM_LX_BOOST_SECURITY_DISABLED	(0)
#define EEPROM_LX_BOOST_SECURITY_ENABLED	(EEPROM_NETBOOK2_ERASED_VALUE)
#define EEPROM_LX_BOOST_SECURITY_LOCKDOWN	(2)

/* /dev/nvram ioctls */
#define NVRAM_UNLOCK_TOUCH_CALIBRATION  _IO('p', 0x42)
